name: graphql_code_builder_flutter
version: 1.0.0
description: Dart code builders taking *.graphql documents and SDL to build useful classes.

environment:
  sdk: '>=2.12.0 <3.0.0'
dependencies: 
  analyzer: ^2.3.0
  built_collection: ^5.0.0
  built_value: ^8.0.6
  code_builder: ^4.0.0
  collection: ^1.15.0
  gql: ^0.13.1-alpha
  gql_exec: 0.3.0
  path: ^1.8.0
dev_dependencies: 
  build_runner: ^2.1.0
  gql_pedantic: ^1.0.2
  test: ^1.16.8
