name: graphql_code_builder_flutter
version: 1.0.3
description: Dart code builders taking *.graphql documents and SDL to build useful classes.

environment:
  sdk: '>=2.17.0 <3.0.0'
dependencies: 
  analyzer: 3.4.1
  built_collection: ^5.0.0
  built_value: ^8.0.6
  code_builder: ^4.0.0
  collection: ^1.15.0
  gql: ^0.14.0
  gql_exec: ^0.4.3
  path: ^1.8.0
dev_dependencies: 
  build_runner: ^2.1.0
  gql_pedantic: ^1.0.2
  test: ^1.16.8
